// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { MyCeliumParameters, MyceliumConfig, SharedCore } from "./core.js";
import { InvokeResponse } from "./types.js";

export const getForWebsite = async (
  website: string,
  lastReconnectBundle: MyceliumConfig,
): Promise<InvokeResponse> => {
  const invocationConfig: MyCeliumParameters = {
    name: "ItemsGetForWebsite",
    parameters: {
      website,
    },
  };
  const response = await new SharedCore().invoke(
    invocationConfig,
    lastReconnectBundle,
  );
  return JSON.parse(response) as InvokeResponse;
};
