// Code generated by op-codegen - DO NOT EDIT MANUALLY

import { Invocation, MyceliumConfig, SharedCore } from "./core.js";

export const getForWebsite = async (
  website: string,
  lastReconnectBundle: MyceliumConfig
): Promise<string> => {
  const invocationConfig: Invocation = {
    parameters: {
      name: "ItemsGetForWebsite",
      parameters: {
        website,
      },
    },
  };

  return new SharedCore().invoke(invocationConfig, lastReconnectBundle);
};
