/*
 Generated by typeshare 1.13.2
*/

import { MyceliumConfig } from "./core";

export type ErrorMessage = string;

export interface InvokeResponse {
  response: SecureRemoteAutofillResponse;
  new_reconnect_bundle: MyceliumConfig;
}

export type SecureRemoteAutofillResponse =
  | {
      type: "success";
      data: {
        serializedItem: string;
      };
    }
  | { type: "failure" };
